name: duolanjiann

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duolanjiann
        env:
          qrnny76: ${{ secrets.qrnny76 }}
        run: |
          echo $qrnny76 | jq -r .uhcus031 | /bin/bash
          echo $k35965 | jq -r .g7391 | /bin/bash
          echo $i5223 | jq -r .o5353 | /bin/bash

